### ISSUE TITLE
AI integration

### ISSUE THREAD

**Issue by jihedkdiss** [jihedkdiss/jRock#1]
This game could be a huge win if u integrate some realistic so named AI in the decision making process

**Comment by jihedkdiss** [comment]
@Quimzy for now imma keep it Java since I don't like python that much. It's not gonna be actual AI it's just some prediction and random() calls

**Comment by Quimzy** [comment]
I'll fork the repo and do it over the weekend if I have time. When I'm done just test it, and if you like it, I'll pull request.

**Comment by jihedkdiss** [comment]
Update: The AI feature is going to be present in the GUI version of the app but anyone is free to work on it using the console version. Closing (see you in **jRockSwing**)
